Update mod-pagespeed download and folder
wunderkraut/alpine-nginx-pagespeed pull request #8
Opened 2016-09-30 13:50 UTC by aleksijohansson

This is not working yet and needs more work. It seems mod-pagespeed folder structure has changed (maybe other things too) which is causing our build to fail. Trying to get this setup according to Google's setup instructions https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source

2016-09-30 15:26 UTC, iler commented
@aleksijohansson Note that there are some differences when working with Alpine. Some resources for this:
https://github.com/cchamplin/alpine-ngx-pagespeed
https://github.com/pagespeed/ngx_pagespeed/issues/1166
https://github.com/pagespeed/ngx_pagespeed/issues/1181

2016-09-30 21:24 UTC, aleksijohansson commented
I might suggest we use for example CentOS for Nginx Pagespeed image before Alpine gets better support because CentOS is officially supported even though the image is larger https://github.com/wunderkraut/centos-nginx-pagespeed

2016-10-01 20:53 UTC, aleksijohansson commented
This builds now. @iler maybe you could do a sanity check?

2016-10-01 20:56 UTC, aleksijohansson commented
Fun fact, the size of this image is now 63.83 MB and the size of equivalent CentOS image is 416.9 MB.

2016-10-02 10:47 UTC, iler commented
@aleksijohansson one change for this before we can merge it. We should use Nginx mainline version instead of stable for the reasons explained here https://www.nginx.com/blog/nginx-1-6-1-7-released/

> Note that stable does not mean more reliable or more bug-free. In fact, the mainline is generally regarded as more reliable because we port all bug fixes to it, and not just critical fixes as for the stable branch.

> We recommend that in general you deploy the NGINX mainline branch at all times.

So change the Nginx version to the latest mainline version which is 1.11.4 and then we should be ok to proceed.

2016-10-02 10:48 UTC, iler requested changes
Change Nginx to the latest mainline version 1.11.4

2016-10-03 09:08 UTC, aleksijohansson commented
Updated Nginx to mainline version 1.11.4 and successfully tested the build

2016-10-03 09:40 UTC, iler approved these changes

2016-10-03 09:41 UTC, merged